#1 StressinG Me out
RIT-EVT/SGM pull request #1
Opened 2024-02-23 01:01 UTC by ntr1556

Initial setup for SGM repo. Changed all generic "BOARD_NAME" references to be SGM specific. Updated ReadMe.

2024-02-24 15:11 UTC, ActuallyTaylor approved these changes

2024-02-24 17:33 UTC, mjmagee991 requested changes
A couple things to clean up, but this is a good start

2024-02-24 17:33 UTC, mjmagee991 commented on CMakeLists.txt
> +        src/dev/StrainGauge.cpp
```suggestion
```

2024-02-24 17:33 UTC, mjmagee991 commented on README.md
>  [EVT-core Documentation](https://evt-core.readthedocs.io/)
Why did you delete some of the template stuff, but not all of it?

2024-02-24 17:33 UTC, mjmagee991 commented on README.md
> +    The Strain Gauge Module (SGM) is a PCB capable of reading strain on REV3 in multiple locations. It
```suggestion
The Strain Gauge Module (SGM) is a PCB capable of sensing strain on REV3 in multiple locations. It 
```

2024-02-24 17:33 UTC, mjmagee991 commented on include/SGM.hpp
> +}
```suggestion
}

```

2024-02-24 17:33 UTC, mjmagee991 commented on targets/REV3-SGM/CMakeLists.txt
> +project(BIKE_NAME-SGM)
```suggestion
project(REV3-SGM)
```

2024-02-24 17:33 UTC, mjmagee991 commented on libs/EVT-core
Not exactly sure what's going on, but the build is failing because of your submodule here. Consider reverting it back to the template default for now

2024-03-01 23:48 UTC, mjmagee991 approved these changes
Nice work!

2024-03-08 01:17 UTC, ActuallyTaylor approved these changes

2024-03-18 14:11 UTC, merged